[package]
name = "trace_graphs"
version = "0.1.0"
edition = "2021"

[dependencies]
dslab-mr = { version = "0.1.0", path = "../../crates/runtime" }
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.117"
plotters = "0.3.5"
