initial_data: 256
stages:
  - tasks:
    - time_per_byte: 300
      output_size_ratio: 2
    - time_per_byte: 350
      output_size_ratio: 2
  - tasks:
    - time_per_byte: 100
      output_size_ratio: 0.1
    - time_per_byte: 110
      output_size_ratio: 0.1
    upload_result_to_dfs: true
    connections:
      - from: 0
        shuffle: Simple
